name: clans
version: '${project.version}'
main: me.abacate.clans.Clans
api-version: '1.20'
commands:
  addClan:
    description: "Cria um Clã"
    usage: /addClan
  deleteClan:
    description: "Deleta um Clã (é para sempre e sem verificação)"
    usage: /deleteClan
  addEnemy:
    description: "Adiciona um inimigo"
    usage: /addEnemy
  sendInvite:
    description: "Manda um convite para outro jogador entra no clã"
    usage: /sendInvite
  acceptInvite:
    description: "Aceita convite para entrar em clã"
    usage: /acceptInvite
  rejectInvite:
    description: "Rejeita convite para entrar em clã"
    usage: /rejectInvite
  sendAllyInvite:
    description: "Manda um convite de aliado para outro clã"
    usage: /sendAllyInvite
  acceptAllyInvite:
    description: "Aceita convite de aliado"
    usage: /acceptAllyInvite
  rejectAllyInvite:
    description: "Rejeita convite de aliado"
    usage: /rejectAllyInvite
  leaveClan:
    description: "Sair do clã"
    usage: /leaveClan
  removeAlly:
    description: "Remove aliado"
    usage: /removeAlly
  removeEnemy:
    description: "Remove inimigo"
    usage: /removeEnemy
  removeMember:
    description: "Remove membro"
    usage: /removeMember
  setPrefix:
    description: "Seta a tag do clã, em MAIUSCULO com no maximo 4 letras"
    usage: /setPrefix
#  toggleChat:
#    description: "Troca o chat para o chat do clã"
#    usage: /toggleChat
#  openClanChest:
#    usage: /openClanInventory
permissions:
  clans.add:
    description: "Permissão para criar um clã"
    default: true
  clans.delete:
    description: "Permissão para deletar um clã"
    default: true
  clans.addEnemy:
    description: "Permissão para adicionar um inimigo"
    default: true
  clans.sendInvite:
    description: "Permissão para enviar um convite para entrar no clã"
    default: true
  clans.acceptInvite:
    description: "Permissão para aceitar um convite para entrar no clã"
    default: true
  clans.rejectInvite:
    description: "Permissão para rejeitar um convite para entrar no clã"
    default: true
  clans.sendAllyInvite:
    description: "Permissão para enviar um convite de aliado"
    default: true
  clans.acceptAllyInvite:
    description: "Permissão para aceitar um convite de aliado"
    default: true
  clans.rejectAllyInvite:
    description: "Permissão para rejeitar um convite de aliado"
    default: true
  clans.leave:
    description: "Permissão para sair do clã"
    default: true
  clans.removeAlly:
    description: "Permissão para remover um aliado"
    default: true
  clans.removeEnemy:
    description: "Permissão para remover um inimigo"
    default: true
  clans.removeMember:
    description: "Permissão para remover um membro"
    default: true
  clans.setPrefix:
    description: "Permissão para definir a tag do clã"
    default: true